### ISSUE TITLE
dora,antd-tools,ant-tool,atool-build是什么关系？

### ISSUE THREAD

**Issue by lefter** [ant-design/antd-tools#17]
搞晕了，这几个工具是什么关系，怎么分工的？
antd-tools
https://github.com/ant-design/antd-tools

ant-tool
https://github.com/ant-tool

atool-build
https://github.com/ant-tool/atool-build/

dora
https://github.com/dora-js/dora

dora-plugin-webpack
https://github.com/dora-js/dora-plugin-webpack

**Comment by benjycui** [comment]
`antd-tools` 是用于开发 `antd` `antd-mobile` 的工具，不是 contributor 的话请无视。

ant-tool dora 相关请去阅读对应的文档。
