### ISSUE TITLE
upgrade old dependencies

### ISSUE THREAD

**Issue by afc163** [ant-design/antd-tools#28]

**Comment by paranoidjk** [comment]
upgrade to atool-build 1.x, for antd-mobile@2.0 https://github.com/ant-design/ant-design-mobile/pull/1632

**Comment by yesmeck** [comment]
@paranoidjk https://github.com/ant-design/antd-tools/blob/master/lib/getWebpackConfig.js#L49-L59 这里需要调整吗？
