### ISSUE TITLE
add es folder

### ISSUE THREAD

**Issue by yiminghe** [ant-design/antd-tools#39]
https://github.com/react-component/rc-tools/commit/2c37699ee9051a0302feb8cb6138c5c2ccb0fe4e

https://github.com/rollup/rollup/wiki/pkg.module

**Comment by paranoidjk** [comment]
- [rc-tabs](https://github.com/react-component/tabs/compare/96755a6e07bed9ab344b5239405270d3d30d7580...2ff5b53102a6d57cba0bed656685b69e36969f08) 昨天的版本已经加了
