### ISSUE TITLE
tslint global varaiable

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/antd-tools#53]
```bash
components/index.tsx(2,13): error TS2304: Cannot find name 'process'.
```

such as: process https://github.com/ant-design/ant-design/blob/master/components/index.tsx#L2

https://github.com/ant-design/antd-tools/blob/master/lib/tslint.json

**Comment by yesmeck** [comment]
这个不是 tslint 报的。

**Comment by paranoidjk** [comment]
typescript compiler 报的 https://stackoverflow.com/questions/35666903/typescript-definitions-for-process-env-node-env

**Comment by paranoidjk** [comment]
npm install --save-dev @types/node
就好了。

antd 也可以加下。

**Comment by paranoidjk** [comment]
npm install --save-dev @types/node
就好了。

antd 也可以加下。
