### ISSUE TITLE
clean typescript compiler result at the same time

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/antd-tools#55]
https://github.com/ant-design/antd-tools/blob/master/lib/gulpfile.js#L64

cc @yesmeck

**Comment by yesmeck** [comment]
加个参数不要输出 js 文件就可以了

**Comment by yesmeck** [comment]
`--noEmit`

**Comment by paranoidjk** [comment]
现有有 jsx ,js 两个产物

**Comment by yesmeck** [comment]
tsx => jsx ts => js

**Comment by paranoidjk** [comment]
尝试了 clean 掉所有 compile output 之后重新 run pub，还是挂两个

<img width="611" alt="2017-08-01 21 41 40" src="https://user-images.githubusercontent.com/7971415/28828093-3f07ab56-7702-11e7-8e8c-3229834b8660.png">
<img width="861" alt="2017-08-01 21 41 46" src="https://user-images.githubusercontent.com/7971415/28828091-3ef11eae-7702-11e7-9c81-d0cf7c8f7fb1.png">

**Comment by paranoidjk** [comment]
@yesmeck 在什么时候加 noEmit 都不太合适吧？我们的 build，pub，lib test 等等场景都是需要生成构建文件的。

这个 clean 的先不管了。我继续看看这个 pub 报错

**Comment by paranoidjk** [comment]
https://github.com/ant-design/ant-design-mobile/blob/master/.jest.js#L5

https://github.com/react-component/m-date-picker/blob/master/package.json#L73
