### ISSUE TITLE
Move svg loader config from antd-mobile project to antd-tools

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/antd-tools#56]
eg:  [rc-tools](https://github.com/react-component/rc-tools/blob/master/lib/getWebpackCommonConfig.js#L61), when tiny app build  with rc-tools, the tiny project no need to set svg-sprite-loader

cc @silentcloud @warmhug

**Comment by silentcloud** [comment]
@paranoidjk 没能根本解决问题，文档还是得有，用户还是得配，仅仅是从库里移出去而已

**Comment by paranoidjk** [comment]
@silentcloud 这个是简化 antd-mobile 仓库本身，不是对用户的

**Comment by paranoidjk** [comment]
对用户的 svg icon 这一块的简化

@warmhug 有在讨论，可以写下方案

**Comment by silentcloud** [comment]
嗯 我明白，但是 这个对于 antd 来说不会用到，放到 atnd-mobile 反而合适

**Comment by paranoidjk** [comment]
我的想法是， antd-mobile 项目本身的所有构建，都由 antd-tools 的命令包裹掉。

这就是 antd-tools, rc-tools 的定位，来集中管控所有我们项目本身的构建需求。

**Comment by paranoidjk** [comment]
> 但是 这个对于 antd 来说不会用到，放到 atnd-mobile 反而合适

rc-tools 的 svg loader 要说更没有。

只是我们自产的 tools，自包含所有需求最好。

**Comment by warmhug** [comment]
工具问题，不是 边柳 以后主要负责吗，可以拉上讨论 @yesmeck

**Comment by benjycui** [comment]
@yesmeck 主要是搞 atool 。。。

**Comment by paranoidjk** [comment]
close. 

Since antd-mobile@2.0 decide to split svg icon into a single npm package and make it optional.
