### ISSUE TITLE
不考虑兼容下window操作系统吗？

### ISSUE THREAD

**Issue by guxingke201** [ant-design/antd-tools#67]
`if (file.path.match(/\/style\/index\.less$/) || file.path.match(/\/style\/v2-compatible-reset\.less$/)) {`
类似这种路径匹配的，在window系统下会匹配失败，最终导致没有编译less文件，这种使用场景不考虑吗？

**Comment by yesmeck** [comment]
因为团队里没有 Windows 用户。欢迎 PR。
