### ISSUE TITLE
upgrade deps

### ISSUE THREAD

**Issue by afc163** [ant-design/antd-tools#74]
https://david-dm.org/ant-design/antd-tools

**Comment by chenyang-biu** [comment]
@afc163  关于提升灯塔分数 初步我先升到webpack4 babel7, 及其他最新依赖 并 对webpack config 做一些优化， 然后根据 lighthome 的指导制定一些优化方案, 大佬觉得如何 求指点

**Comment by afc163** [comment]
@chenyang-biu 就这么干，加油。

**Comment by chenyang-biu** [comment]
@afc163 恩啊

**Comment by bang88** [comment]
这个什么时候能升级，rn那边升级到57后歇菜了。 这边的jest还是旧版的

**Comment by chenyang-biu** [comment]
@bang88 最多俩星期，家中有事情，国庆前回去了， 还在老家， 我晚上尽快 先把部分依赖更新掉

**Comment by chenyang-biu** [comment]
![screenshot from 2018-09-19 22-27-40](https://user-images.githubusercontent.com/20581031/48009409-a666eb80-e156-11e8-8d3f-7706806e68e3.png)
请教下,  我应该把gulp 任务单独拆分到一个目录么， 感觉gulp文件太大了, webpack那个目录请忽视， 现在已经在getWebpackConfig.js 上边改了,

另外 getWebpackConfig.js 没用, 相应的gulp task 要不要做一个检测， 如果项目没有webpack config.js就使用getWebpackConfig.js

另外有slack或者gitter可以讨论么

**Comment by chenyang-biu** [comment]
@bang88  @afc163  
       [#PR79](https://github.com/ant-design/antd-tools/pull/79), 
        麻烦审下， 我明晚审，
       然后，有不合理， 或者有更好的实现方法评论就行， 
       合理的有多少改多少 
       合并请求没拆，忍忍....... = =
