### ISSUE TITLE
replaceLib是否有存在必要？

### ISSUE THREAD

**Issue by ahungrynoob** [ant-design/antd-tools#83]
看源代码，antd-tools run compile 的时候只是针对带有'lib'的路径的模块进行node-modules的es路径替换，很多不带lib的模块路径比如`import Animate from 'rc-animate';`实际上还是以commonjs方式在es代码中引入的。。。然后antd-tools run dist 利用webpack 还是能打包出文件。那这样做的意义是什么，

**Comment by yesmeck** [comment]
把

```javascript
import xx from 'foo/lib/xx';
```

替换成

```javascript
import xx from 'foo/es/xx';
```

`import Animate from 'rc-animate';` 这种情况 webpack 自己会判断用哪种 module 格式。

**Comment by ahungrynoob** [comment]
感谢
