### ISSUE TITLE
Improve antd-tools publish

### ISSUE THREAD

**Issue by afc163** [ant-design/antd-tools#95]
Background: https://github.com/ant-design/ant-design/issues/15790

- [ ] Check all files in dist before publish: unpkg.com/antd/dist/
- [ ] Exit if git status is dirty.

**Comment by afc163** [comment]
Further solution: https://medium.com/devopslinks/automate-your-npm-publish-with-github-actions-dfe8059645dd

**Comment by yesmeck** [comment]
发布前 diff 一下文件的变动，类似 `git status`
